import { badRequest } from "./respond.js";

const PLATFORMS = ["telegram", "bale", "whatsapp"];
const EVENT_TYPES = ["created", "published", "updated", "deleted", "deleted_from_trash"];
const PUBLICATION_STATUSES = ["published", "failed", "skipped", "deleted", "superseded", "blocked", "unsupported"];

export const PLATFORM_VALUES = Object.freeze(PLATFORMS);
export const EVENT_TYPE_VALUES = Object.freeze(EVENT_TYPES);
export const PUBLICATION_STATUS_VALUES = Object.freeze(PUBLICATION_STATUSES);

export function requireString(value, field, { min = 1, max = 255 } = {}) {
  const text = String(value ?? "").trim();
  if (text.length < min) throw badRequest(`${field} is required`);
  if (text.length > max) throw badRequest(`${field} must be at most ${max} characters`);
  return text;
}

export function optionalString(value, field, { max = 255 } = {}) {
  if (value === undefined || value === null) return "";
  const text = String(value).trim();
  if (text.length > max) throw badRequest(`${field} must be at most ${max} characters`);
  return text;
}

/** Accepts only absolute http(s) URLs — no javascript:, no relative paths. */
export function requireUrl(value, field = "url") {
  const text = requireString(value, field, { max: 2048 });
  let parsed;
  try {
    parsed = new URL(text);
  } catch {
    throw badRequest(`${field} must be a valid URL`);
  }
  if (!["http:", "https:"].includes(parsed.protocol)) throw badRequest(`${field} must use http or https`);
  if (!parsed.hostname) throw badRequest(`${field} must include a hostname`);
  return parsed.toString().replace(/\/+$/, "");
}

export function optionalUrl(value, field = "url") {
  if (value === undefined || value === null || String(value).trim() === "") return "";
  return requireUrl(value, field);
}

export function requireEnum(value, allowed, field) {
  const text = String(value ?? "").trim();
  if (!allowed.includes(text)) throw badRequest(`${field} must be one of: ${allowed.join(", ")}`);
  return text;
}

export function optionalEnum(value, allowed, field) {
  if (value === undefined || value === null || String(value).trim() === "") return undefined;
  return requireEnum(value, allowed, field);
}

export function requireInt(value, field, { min = Number.MIN_SAFE_INTEGER, max = Number.MAX_SAFE_INTEGER } = {}) {
  const number = Number(value);
  if (!Number.isFinite(number) || !Number.isInteger(number)) throw badRequest(`${field} must be an integer`);
  if (number < min || number > max) throw badRequest(`${field} must be between ${min} and ${max}`);
  return number;
}

export function optionalInt(value, field, options) {
  if (value === undefined || value === null || String(value).trim() === "") return undefined;
  return requireInt(value, field, options);
}

export function requireBoolean(value, field) {
  if (typeof value === "boolean") return value;
  const text = String(value ?? "").trim().toLowerCase();
  if (["true", "1", "yes"].includes(text)) return true;
  if (["false", "0", "no"].includes(text)) return false;
  throw badRequest(`${field} must be a boolean`);
}

export function optionalBoolean(value, field) {
  if (value === undefined || value === null || String(value).trim() === "") return undefined;
  return requireBoolean(value, field);
}

/** Site ids are generated by the backend; accept only that shape. */
export function requireSiteId(value, field = "site_id") {
  const text = requireString(value, field, { max: 64 });
  if (!/^[A-Za-z0-9_.:-]{3,64}$/.test(text)) throw badRequest(`${field} has an invalid format`);
  return text;
}

export function optionalSiteId(value, field = "site_id") {
  if (value === undefined || value === null || String(value).trim() === "") return undefined;
  return requireSiteId(value, field);
}

export function requireTelegramUserId(value, field = "telegram_id") {
  const text = requireString(value, field, { max: 20 });
  if (!/^\d{3,20}$/.test(text)) throw badRequest(`${field} must be a numeric Telegram id`);
  return text;
}

export function optionalTelegramUserId(value, field = "telegram_id") {
  if (value === undefined || value === null || String(value).trim() === "") return "";
  return requireTelegramUserId(value, field);
}

/**
 * A Telegram channel target: @username, a t.me link (normalized to @username),
 * or a numeric chat id such as -1001234567890.
 */
export function optionalTelegramTarget(value, field = "telegram_channel_id") {
  const raw = String(value ?? "").trim();
  if (!raw) return "";
  const link = raw.match(/^(?:https?:\/\/)?(?:www\.)?t\.me\/([A-Za-z0-9_]{4,32})\/?$/i);
  if (link) return `@${link[1]}`;
  if (/^@[A-Za-z0-9_]{4,32}$/.test(raw)) return raw;
  if (/^-?\d{5,20}$/.test(raw)) return raw;
  throw badRequest(`${field} must be @username, a t.me link, or a numeric chat id`);
}

/** Bale accepts @usernames and numeric chat ids. */
export function optionalBaleTarget(value, field = "bale_chat_id") {
  const raw = String(value ?? "").trim();
  if (!raw) return "";
  if (/^@[A-Za-z0-9_]{4,32}$/.test(raw)) return raw;
  if (/^-?\d{3,20}$/.test(raw)) return raw;
  throw badRequest(`${field} must be @username or a numeric chat id`);
}

/** E.164-ish msisdn used as a WhatsApp recipient. */
export function optionalPhone(value, field = "phone") {
  const raw = String(value ?? "").trim();
  if (!raw) return "";
  const digits = raw.replace(/[\s()-]/g, "");
  if (!/^\+?\d{8,15}$/.test(digits)) throw badRequest(`${field} must be a valid phone number`);
  return digits;
}

export function optionalDate(value, field) {
  if (value === undefined || value === null || String(value).trim() === "") return undefined;
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) throw badRequest(`${field} must be a valid date`);
  return date.toISOString();
}

export const requirePlatform = (value, field = "platform") => requireEnum(value, PLATFORMS, field);
export const optionalPlatform = (value, field = "platform") => optionalEnum(value, PLATFORMS, field);
